version: '3.8'
services:
  postgres:
    image: postgres:latest    
    environment: 
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: 123 
      POSTGRES_DB: grocery_app   
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data             
  app:
    build: .
    container_name: grocery_app
    environment:
      JWT_SECRET: string
      DATABASE_URL: postgresql://root:123@postgres:5432/grocery_app?schema=private
      PRISMA_CLI_QUERY_ENGINE_TYPE: binary
    volumes:
      - '.:/app'
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    restart: always
    command: sh -c "npx prisma migrate dev --name init && npm start"
volumes:
  postgres-data:
